// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: people.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePeopleReq_Position int32

const (
	CreatePeopleReq_STUDENT    CreatePeopleReq_Position = 0
	CreatePeopleReq_TEACHER    CreatePeopleReq_Position = 1
	CreatePeopleReq_PROGRAMMER CreatePeopleReq_Position = 2
)

// Enum value maps for CreatePeopleReq_Position.
var (
	CreatePeopleReq_Position_name = map[int32]string{
		0: "STUDENT",
		1: "TEACHER",
		2: "PROGRAMMER",
	}
	CreatePeopleReq_Position_value = map[string]int32{
		"STUDENT":    0,
		"TEACHER":    1,
		"PROGRAMMER": 2,
	}
)

func (x CreatePeopleReq_Position) Enum() *CreatePeopleReq_Position {
	p := new(CreatePeopleReq_Position)
	*p = x
	return p
}

func (x CreatePeopleReq_Position) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreatePeopleReq_Position) Descriptor() protoreflect.EnumDescriptor {
	return file_people_proto_enumTypes[0].Descriptor()
}

func (CreatePeopleReq_Position) Type() protoreflect.EnumType {
	return &file_people_proto_enumTypes[0]
}

func (x CreatePeopleReq_Position) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreatePeopleReq_Position.Descriptor instead.
func (CreatePeopleReq_Position) EnumDescriptor() ([]byte, []int) {
	return file_people_proto_rawDescGZIP(), []int{0, 0}
}

type CreatePeopleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age      int64                     `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	ExtMsg   *string                   `protobuf:"bytes,3,opt,name=extMsg,proto3,oneof" json:"extMsg,omitempty"`
	Position *CreatePeopleReq_Position `protobuf:"varint,4,opt,name=position,proto3,enum=CreatePeopleReq_Position,oneof" json:"position,omitempty"`
}

func (x *CreatePeopleReq) Reset() {
	*x = CreatePeopleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_people_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePeopleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeopleReq) ProtoMessage() {}

func (x *CreatePeopleReq) ProtoReflect() protoreflect.Message {
	mi := &file_people_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeopleReq.ProtoReflect.Descriptor instead.
func (*CreatePeopleReq) Descriptor() ([]byte, []int) {
	return file_people_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePeopleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePeopleReq) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreatePeopleReq) GetExtMsg() string {
	if x != nil && x.ExtMsg != nil {
		return *x.ExtMsg
	}
	return ""
}

func (x *CreatePeopleReq) GetPosition() CreatePeopleReq_Position {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return CreatePeopleReq_STUDENT
}

type CreatePeopleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      int64  `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreatePeopleRsp) Reset() {
	*x = CreatePeopleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_people_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePeopleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeopleRsp) ProtoMessage() {}

func (x *CreatePeopleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_people_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeopleRsp.ProtoReflect.Descriptor instead.
func (*CreatePeopleRsp) Descriptor() ([]byte, []int) {
	return file_people_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePeopleRsp) GetOk() int64 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *CreatePeopleRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_people_proto protoreflect.FileDescriptor

var file_people_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xde,
	0x01, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x4d,
	0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x65, 0x78, 0x74, 0x4d,
	0x73, 0x67, 0x88, 0x01, 0x01, 0x12, 0x3a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x01, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01,
	0x01, 0x22, 0x34, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x54, 0x55, 0x44, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x45,
	0x41, 0x43, 0x48, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x47, 0x52,
	0x41, 0x4d, 0x4d, 0x45, 0x52, 0x10, 0x02, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x65, 0x78, 0x74, 0x4d,
	0x73, 0x67, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x3b, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x52,
	0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x43, 0x0a, 0x0d,
	0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x10, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x52, 0x73,
	0x70, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_people_proto_rawDescOnce sync.Once
	file_people_proto_rawDescData = file_people_proto_rawDesc
)

func file_people_proto_rawDescGZIP() []byte {
	file_people_proto_rawDescOnce.Do(func() {
		file_people_proto_rawDescData = protoimpl.X.CompressGZIP(file_people_proto_rawDescData)
	})
	return file_people_proto_rawDescData
}

var file_people_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_people_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_people_proto_goTypes = []interface{}{
	(CreatePeopleReq_Position)(0), // 0: CreatePeopleReq.Position
	(*CreatePeopleReq)(nil),       // 1: CreatePeopleReq
	(*CreatePeopleRsp)(nil),       // 2: CreatePeopleRsp
}
var file_people_proto_depIdxs = []int32{
	0, // 0: CreatePeopleReq.position:type_name -> CreatePeopleReq.Position
	1, // 1: PeopleService.CreatePeople:input_type -> CreatePeopleReq
	2, // 2: PeopleService.CreatePeople:output_type -> CreatePeopleRsp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_people_proto_init() }
func file_people_proto_init() {
	if File_people_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_people_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePeopleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_people_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePeopleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_people_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_people_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_people_proto_goTypes,
		DependencyIndexes: file_people_proto_depIdxs,
		EnumInfos:         file_people_proto_enumTypes,
		MessageInfos:      file_people_proto_msgTypes,
	}.Build()
	File_people_proto = out.File
	file_people_proto_rawDesc = nil
	file_people_proto_goTypes = nil
	file_people_proto_depIdxs = nil
}
